### ISSUE TITLE
You can't build on linux

### ISSUE THREAD

**Issue by JJoeDev** [RamezzE/QuadTree-SFML#2]
main.cpp includes <windows.h> and windows header file is not available on linux. You would need to make a macro that checks if you are on a posix system or windows and then includes the system specific includes

**Comment by RamezzE** [comment]
@JJoeDev I updated the CMakeLists.txt to work with windows as well. Can you recheck that it is still working on linux after the merge?

**Comment by JJoeDev** [comment]
There seems to be some issues, well a lot of issues. I will try to get a fix ready

**Comment by RamezzE** [comment]
Last merge didn't work on linux for me. I changed it to use pure Make without CMake for it to run on linux and it works perfectly. Updated Read Me with new steps to build on linux.
